---
- name: Update apt cache
  ansible.builtin.command: sudo apt-get update -qq
  changed_when: false

- name: Install essential packages
  ansible.builtin.command: >
    sudo apt-get install -y -qq
    build-essential curl wget git git-lfs tree nmap zsh neovim unzip fontconfig
  changed_when: false
