---
- name: Copy git configuration files
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ ansible_env.HOME }}/{{ item }}"
    mode: "0644"
    backup: true
  loop:
    - .gitconfig
    - .gitconfig-personal
    - .gitconfig-company
    - .gitignore_global
