---
- name: Check if Xcode Command Line Tools are installed
  ansible.builtin.command: xcode-select --print-path
  register: xcode_check
  changed_when: false
  failed_when: false

- name: Install Xcode Command Line Tools
  ansible.builtin.command: xcode-select --install
  when: xcode_check.rc != 0
